name: 'Deploy applications to Argo CD'
description: 'Send applications to Argo CD when to occur project deploy.'
author: 'Robson Andrade<robson.andrade@contraktor.com.br>'
inputs:
  aws-access-key-id:
    description: ' AWS secret key'
    require: true
  aws-secret-access-key:
    description: ' AWS secret'
    require: true
  owner:
    description: 'organization of github'
    require: true
  environment:
    description: 'the application environment ( dev, stg, prod )'
    require: true
  username:
    description: 'username who will commit the application to argo cd'
    require: true
  gh-token:
    description: 'token of github'
    require: true
  repository-name:
    description: 'repository that will be cloned'
    require: true
  app-name:
    description: 'application name'
    require: true
  platform-name:
    description: 'application platform'
    require: true
  path-name:
    description: 'path of environment and platform'
    require: true
  email:
    description: 'email of user who will commit the application to argo cd'
    require: true
  influxdb-token:
    description: 'token to access influxdb instance'
    require: true
  influxdb-url:
    description: 'url to influxdb instance'
    require: true
  slack-hook:
    description: 'token connect Slack'
    require: true
  argocd-domain:
    description: 'domain intern of Argo CD'
    require: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: get app data
      id: app
      shell: bash
      env:
        IMAGE: ${{ inputs.app-name }}
        GHCR: 'ghcr.io'
        OWNER: ${{ inputs.owner }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        version=`git rev-parse --short HEAD`
        commit_message=`git log -1 --format=%s`
        commit_author_name=`git log -1 --format=%an`
        commit_author_email=`git log -1 --format=%ae`
        echo "::set-output name=version::${ENVIRONMENT}-$version"
        echo "::set-output name=image::$IMAGE"
        echo "::set-output name=ghcr::$GHCR/$OWNER"
        echo "::set-output name=commit_message::${commit_message}"
        echo "::set-output name=commit_author_name::${commit_author_name}"
        echo "::set-output name=commit_author_email::${commit_author_email}"

    - name: tag docker image to ecr
      shell: bash
      env:
        ECR: ${{ steps.login-ecr.outputs.registry }}
        VERSION: ${{ steps.app.outputs.version }}
        IMAGE: ${{ steps.app.outputs.image }}
      run: |
        docker tag $IMAGE:latest $ECR/$IMAGE:$VERSION

    - name: tag docker image to ghcr
      shell: bash
      env:
        ECR: ${{ steps.login-ecr.outputs.registry }}
        VERSION: ${{ steps.app.outputs.version }}
        IMAGE: ${{ steps.app.outputs.image }}
        GHCR: ${{ steps.app.outputs.ghcr }}
      run: |
        docker tag $ECR/$IMAGE:$VERSION $GHCR/$IMAGE:latest

    - name: docker push to ecr
      shell: bash
      env:
        ECR: ${{ steps.login-ecr.outputs.registry }}
        VERSION: ${{ steps.app.outputs.version }}
        IMAGE: ${{ steps.app.outputs.image }}
      run: |
        docker push $ECR/$IMAGE:$VERSION

    - name: docker login to ghcr
      shell: bash
      env:
        USERNAME: ${{ inputs.username }}
        TOKEN: ${{ inputs.gh-token }}
      run: |
        echo $TOKEN | docker login ghcr.io -u $USERNAME --password-stdin

    - name: docker push to ghcr
      shell: bash
      env:
        ECR: ${{ steps.login-ecr.outputs.registry }}
        IMAGE: ${{ steps.app.outputs.image }}
        GHCR: ${{ steps.app.outputs.ghcr }}
      run: |
        docker push $GHCR/$IMAGE:latest

    - name: set docker image to rollout
      shell: bash
      env:
        ECR: ${{ steps.login-ecr.outputs.registry }}
        VERSION: ${{ steps.app.outputs.version }}
        IMAGE: ${{ steps.app.outputs.image }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        export DOCKER_IMAGE=$ECR/$IMAGE:$VERSION
        envsubst < deploy/rollout-template-${ENVIRONMENT}.yaml > deploy/rollout-${ENVIRONMENT}.yaml

    - name: clone repository
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        OWNER: ${{ inputs.owner }}
        REPOSITORY_NAME: ${{ inputs.repository-name }}
        PATH_NAME: ${{ inputs.path-name }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        git clone -b master https://oauth2:${GH_TOKEN}@github.com/${OWNER}/${REPOSITORY_NAME}.git ${REPOSITORY_NAME}
        cp deploy/rollout-${ENVIRONMENT}.yaml ${REPOSITORY_NAME}/${PATH_NAME}/rollout.yaml

    - name: config user admin of github
      shell: bash
      working-directory: ${{ inputs.repository-name }}
      env:
        USERNAME: ${{ steps.app.outputs.commit_author_name }}
        EMAIL: ${{ steps.app.outputs.commit_author_email }}
      run: |
        git config user.name "${USERNAME}"
        git config user.email "${EMAIL}"

    - name: commit alterations at the github
      shell: bash
      working-directory: ${{ inputs.repository-name }}
      env:
        MESSAGE: ${{ steps.app.outputs.commit_message }}
      run: |
        git commit -am"${MESSAGE}"

    - name: push commit to github
      shell: bash
      working-directory: ${{ inputs.repository-name }}
      run: |
        git push

    - name: send rollback metric to influxdb
      uses: contraktor-tech/datapoint-producer-action@master
      if: |
        success() &&
        (inputs.environment == 'prod') &&
        (contains(github.event.head_commit.message, 'rollback') ||
        contains(github.event.head_commit.message, 'revert'))
      with:
        influxdb-token: ${{ inputs.influxdb-token }}
        influxdb-url: ${{ inputs.influxdb-url }}
        influxdb-measurement: 'rollback'
        app: ${{ inputs.platform-name}}-${{ inputs.app-name }}

    - name: send deploy metric to influxdb
      uses: contraktor-tech/datapoint-producer-action@master
      if: |
        success() &&
        (inputs.environment == 'prod') &&
        (!contains(github.event.head_commit.message, 'rollback') &&
        !contains(github.event.head_commit.message, 'revert'))
      with:
        influxdb-token: ${{ inputs.influxdb-token }}
        influxdb-url: ${{ inputs.influxdb-url }}
        influxdb-measurement: 'deploy'
        app: ${{ inputs.platform-name}}-${{ inputs.app-name }}

    - name: deploy has succeeded - Send notification deploy to Slack
      uses: contraktor-tech/slack-notification-action@v1
      if: ${{ success() }}
      with:
        slack-hook: ${{ inputs.slack-hook }}
        argocd-domain: ${{ inputs.argocd-domain}}
        argocd-app: ${{ inputs.environment}}-${{ inputs.platform-name }}-${{ inputs.app-name }}
        project-name: ${{ inputs.app-name }}
        environment-name: ${{ inputs.environment }}
        deploy-status: 'success'

    - name: deploy has failed - Send notification deploy to Slack
      uses: contraktor-tech/slack-notification-action@v1
      if: ${{ failure() }}
      with:
        slack-hook: ${{ inputs.slack-hook }}
        argocd-domain: ${{ inputs.argocd-domain}}
        argocd-app:  ${{ inputs.environment}}-${{ inputs.platform-name }}-${{ inputs.app-name }}
        project-name: ${{ inputs.app-name }}
        environment-name: ${{ inputs.environment }}
        deploy-status: 'failure'

    - name: delete ghcr packages
      uses: i9cloud-tech/delete-untagged-ghcr-action@master
      if: ${{ always() }}
      with:
        org: ${{ inputs.owner }}
        gh-token: ${{ inputs.gh-token }}
        package-name: ${{ inputs.app-name }}
