name: 'Deploy applications to Argo CD'
description: 'Send applications to Argo CD when to occur project deploy.'
author: 'Robson Andrade<robson.andrade@contraktor.com.br>'
inputs:
  application-name:
    description: 'application name'
    require: true
  image-name:
    description: 'same name of repository'
    require: true 
  repository-name:
    description: 'repository that will be cloned'
    require: true 
  path-name:
    description: 'path of environment and platform'
    require: true
  app-influx-name:
    description: 'name app to send deploy metric to influxdb ( combined name of platform name plus application name )'
    require: true
  project-name:
    description: 'combined name of application name plus platform name '
    require: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: get app version
      id: app
      env:
        IMAGE: ${{inputs.image-name}}
        GHCR: 'ghcr.io'
        OWNER: ${{ secrets.ORG_NAME }}
      run: |
        version=`git rev-parse --short HEAD`
        echo "::set-output name=version::dev-$version"
        echo "::set-output name=image::$IMAGE"
        echo "::set-output name=ghcr::$GHCR/$OWNER"
    
    - name: tag docker image to ghcr
      env:
        ECR: ${{ steps.login-ecr.outputs.registry }}
        VERSION: ${{ steps.app.outputs.version }}
        IMAGE: ${{ steps.app.outputs.image }}
        GHCR: ${{ steps.app.outputs.ghcr }}
      run: |
        docker tag $ECR/$IMAGE:$VERSION $GHCR/$IMAGE:latest
    
    - name: docker push to ecr
      env:
        ECR: ${{ steps.login-ecr.outputs.registry }}
        VERSION: ${{ steps.app.outputs.version }}
        IMAGE: ${{ steps.app.outputs.image }}
      run: |
        docker push $ECR/$IMAGE:$VERSION
    
    - name: docker login to ghcr
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo $TOKEN | docker login ghcr.io -u $USERNAME --password-stdin
    
    - name: docker push to ghcr
      env:
        ECR: ${{ steps.login-ecr.outputs.registry }}
        IMAGE: ${{ steps.app.outputs.image }}
        GHCR: ${{ steps.app.outputs.ghcr }}
      run: |
        docker push $GHCR/$IMAGE:latest

    - name: set docker image to rollout
      shell: bash
      env:
        ECR: ${{ steps.login-ecr.outputs.registry }}
        VERSION: ${{ steps.app.outputs.version }}
        IMAGE: ${{ steps.app.outputs.image }}
      run: |
        export DOCKER_IMAGE=$ECR/$IMAGE:$VERSION
        envsubst < deploy/rollout-template.yaml > deploy/${APPLICATION_NAME}-rollout.yaml

    - name: clone repository 
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        OWNER: ${{ secrets.ORG_NAME }}
        REPOSITORY_NAME: ${{ inputs.repository-name }}
        APPLICATION_NAME: ${{ inputs.application-name }}
        PATH_NAME: ${{ inputs.path-name }}
      run: |
        git clone -b master https://oauth2:${GH_TOKEN}@github.com/${OWNER}/${{REPOSITORY_NAME}}.git ${{REPOSITORY_NAME}}
        cp deploy/${{APPLICATION_NAME}}-rollout.yaml ${{REPOSITORY_NAME}}/${{PATH_NAME}}/${{APPLICATION_NAME}}-rollout.yaml
        cd ${{REPOSITORY_NAME}}/
        
        git remote -v 
        git branch
        git status
    
    - name: config user and commit alterations github
      shell: bash
      env:
        USERNAME: ${{ secrets.USERNAME }}
        EMAIL: ${{ secrets.EMAIL }}
      run: |
        git config user.name ${USERNAME}
        git config user.email ${EMAIL}
        
        git commit -am"Send application to monitoring of Argo CD"
        git push

    - name: send deploy metric to influxdb
      uses: contraktor-tech/datapoint-producer-action@v2
      if: |
        !contains(github.event.head_commit.message, 'rollback') &&
        !contains(github.event.head_commit.message, 'revert')
      with:
        influxdb-token: ${{ secrets.INFLUXDB_TOKEN }}
        influxdb-url: ${{ secrets.INFLUXDB_URL }}
        influxdb-measurement: 'deploy'
        app: ${{ inputs.app-influx-name}}
    
    - name: deploy has succeeded - Send notification deploy to Slack
      uses: contraktor-tech/slack-notification-action@master
      if: ${{ success() }}
      with:
        slack-hook: ${{ secrets.SLACK_HOOK }}
        project-name: ${{ inputs.project-name }}
        environment-name: 'prod'
        deploy-status: 'success'

    - name: deploy has failed - Send notification deploy to Slack
      uses: contraktor-tech/slack-notification-action@master
      if: ${{ failure() }}
      with:
        slack-hook: ${{ secrets.SLACK_HOOK }}
        project-name: ${{ inputs.project-name }}'
        environment-name: 'prod'
        deploy-status: 'failure'
